### ISSUE TITLE
课程命名

### ISSUE THREAD

**Issue by Aurora-b1t** [xBeho1der/BIT-CST#1]
学长好啊，您这里的ECE实习1和2是大一下暑假时的吗，24年上的是STM32和Linux，可以把课程名字改下，更容易让人看出来

**Comment by JiantengChen** [comment]
Hi @Aurora-b1t, 感谢回复。课程安排和教学计划每年都有变动，我是21级的，当时的ECE就是这些项目内容，22级据我所知也是这些的基础上外加了STM32的内容。

**Comment by Aurora-b1t** [comment]
我的意思是，比如嵩天老师小学期的Python（ECE实习1）可以直接命名为Python小学期，这样更加通俗易懂。好吧这只是个无关痛痒的小问题。我只是在尝试熟悉Github所以到处看看hhh
